apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: app-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
        - name: app-deploy-cont
          image: >-
            apache/superset:4.1.2
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false